### ISSUE TITLE
interested in supporting multiple realms per request?

### ISSUE THREAD

**Issue by beaugunderson** [nbrochu/requests-respectful#2]
I have [a fork](https://github.com/beaugunderson/requests-respectful) where I've added this because we needed the functionality... I didn't make it entirely backwards-compatible ('realm' argument changed to 'realms' in a lot of places) but it could be if you're interested in merging it. :)

I also fixed some tests and added Python 2 support (we're still stuck on it).

**Comment by nbrochu** [comment]
Just curious: Could you give me a simple sample scenario where multiple realms per request is required?Aside from breaking the current API, I'm interested in seeing if this is a common use case or totally fringe. I wouldn't be opposed to adding that at all.

**Comment by beaugunderson** [comment]
I added it so we could have per-user realms (fitbit gives you 150 requests per access token per hour) plus a realm for all fitbit requests so we don't exceed 10,000 requests an hour among all users.

One way to not break the current API might be to support both a "realm" and a "realms" parameter?

---

**Comment by nbrochu** [comment]
Two months later... Added in #5
