### ISSUE TITLE
workflow for using configuration stored in the environment

### ISSUE THREAD

**Issue by beaugunderson** [nbrochu/requests-respectful#3]
If you import any of the modules and then try to set the configuration you'll get an exception because the redis connection test will fail.

**Comment by nbrochu** [comment]
I'll take a look tomorrow. Thanks.

**Comment by beaugunderson** [comment]
added to my fork if you want to steal the technique :)

---

**Comment by nbrochu** [comment]
I addressed the immediate connection check for Redis. You can now load the module, configure and then load up an instance.
